
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}


spring.datasource.hikari.maximum-pool-size=${DB_POOL_MAX:20}
spring.datasource.hikari.minimum-idle=${DB_POOL_MIN:4}
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000


spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never


logging.level.root=WARN
logging.level.com.backendpill=INFO